from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIModel

#TODO include a graph representation of the codebase

def summarize_iac_changes(diff, codebase_original_sha):

    model = OpenAIModel('gpt-4o')
    agent = Agent(  
        model,
        system_prompt='Given a diff generated by git, as well as all the relevant files and their paths from before the diff was applied, summarize any Terraform changes and the implications those changes may have, especially on security. Pay special attention to any IAM roles and policies, but also look holistically at any Terraform changes. Help the user understand the high level security implications and the code changes overall. Output your result with valid markdown in the form of documentation for the diff that is easy for a newcomer to the project to understand.',  
    )
    llm_input_string = "*** Here are the changes made to the codebase in diff format:\n\n" + diff + "\n\n*** Here is the original codebase: \n\n" + codebase_original_sha
    result = agent.run_sync(llm_input_string)  
    print(result.output)
