from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIModel


def summarize_iac_changes(diff):

    model = OpenAIModel('gpt-4o')
    agent = Agent(  
        model,
        system_prompt='Given a diff generated by git, summarize any Terraform changes and the implications those changes may have, especially on security. Pay special attention to any IAM roles and policies, but also look holistically at any Terraform changes. Help the user understand the high level security implications and the code changes overall. Output your result with valid markdown in the form of documentation for the diff that is easy for a newcomer to the project to understand.',  
    )
    result = agent.run_sync(diff)  
    print(result.output)
